# Generated by Django 4.1.5 on 2023-01-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_scrapingtask_user_text_scrapingtask_new_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(),
        ),
    ]
