# Generated by Django 4.1.5 on 2023-01-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_link_product_url_product_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='product_id',
        ),
    ]
