# Generated by Django 4.1.5 on 2023-01-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_scrapingtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingtask',
            name='user_text',
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='New_ids',
            field=models.TextField(default='Enter ids here', max_length=1000),
        ),
    ]
