# Generated by Django 4.1.5 on 2023-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('title', models.CharField(default='Default title', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default='0,00', max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, default='0,00', max_digits=10)),
                ('brand', models.CharField(default='Default title', max_length=50)),
                ('link', models.CharField(default='Default link', max_length=50)),
            ],
        ),
    ]
